# Nombre del Workflow
name: Build and Deploy GitHub Pages

# Disparadores: se ejecuta en cada push a la rama 'main'
on:
  push:
    branches:
      - main  # O la rama que uses como principal (ej. master)

# Permisos necesarios para el job
permissions:
  contents: write # Para poder hacer commit del structure.json
  pages: write    # Para poder desplegar en GitHub Pages
  id-token: write # Necesario para la autenticación del despliegue

# Define los jobs que se ejecutarán
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Se ejecuta en una máquina virtual con Ubuntu

    steps:
      # 1. Checkout del repositorio
      # Descarga el código de tu repositorio a la máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configuración de Node.js
      # Instala Node.js para poder ejecutar el script
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Usamos una versión LTS de Node.js
        #   cache: 'npm' # Opcional: cachea las dependencias si las tuvieras

      # 3. Ejecutar el script para generar structure.json
      # Corre el script que hemos creado para escanear los directorios
      - name: Generate structure.json
        run: node scripts/generate-structure.mjs

      # 4. Hacer commit del archivo structure.json generado
      # Si el script ha creado o modificado structure.json, este paso lo añade al repositorio
      - name: Commit structure.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Auto-generate portfolio structure'
          file_pattern: 'structure.json'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>'

      # 5. Subir el artefacto para el despliegue
      # Empaqueta todo el sitio para que GitHub Pages pueda usarlo
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Sube el contenido del directorio raíz

      # 6. Desplegar en GitHub Pages
      # Este paso toma el artefacto subido y lo publica
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
